

vector_field:
    vr: 0.5 # reference forward speed for the vector field
    kf: 5.0 # convergence gain of the vector field
    reverse_direction: False # flag to invert the direction the curve will be followed

groundrobot:
    d_feedback: 0.1 # distance of the controlled point of the feedback linearization controller
    move_backwards: False # flag to make the robot move backwards
    a: 0.18
    b: 0.11

topics:
    pose_topic_name: "skidsteer/pose" # name of the topic in which the pose will be obtained
    pose_topic_type: "Pose" # Options: 'TFMessage', 'Pose' or 'Odometry'
    #cmd_vel_topic_name: "skidsteer/cmd_vel" # name of the topic in which the forward and angular velocities will be published
    cmd_wheels_topic_name: "skidsteer/wheels_speeds" # name of the topic in which the rigth and left speeds will be piblished
    path_topic_name: "example_path" # name of the topic in which the path will be published
    path_equation_topic_name: "example_path_equation" # name of the topic in which the path will be published (equation form)

#Collision avoidance considering the closest point in the body frame - specific for ground robots
obstacle_avoidance:
    flag_follow_obstacle: True # flag to enable the robot to follow an obstacle when it s blocking the vector field
    epsilon: 0.35 # reference distance between the robot and the path being followed
    switch_dist_0: 0.8 # distance from which the robot will start to follow the obstacle
    switch_dist: 0.6 # distance from which the robot will start to follow the obstacle
    obstacle_point_topic_name: "skidsteer/closest_point_body" # name of the topic in which the laser data will be obtained
